### ISSUE TITLE
Error Parsing Result XML:  Start tag expected.

### ISSUE THREAD

**Issue by dawnbuie** [kevinhendricks/ePub3-itizer#3]
HI there

My epub2 document passed FlightCrew validation, however when I run  ePub3-itizer v036, it looks like all is going well

..parsing: OEBPS/toc.ncx
..creating: OEBPS/nav.xhtml
..creating: epub3

but then the process stalls.
I then hit Cancel and get this error message: `Error Parsing Result XML:  Start tag expected.`

Then I see:

```
Plugin cancelled
Launcher process crashed
```

Do you know what might be causing this?

thanks

**Comment by kevinhendricks** [comment]
My guess is it actually did not stall - it just appeared that way to you.  It was waiting for you to tell it where to save the new epub3 and what to call it.   You just probably did not notice that the plugin had launched a python Tk gui filebrowser to ask you to select a name and path for the newly created epub3.  It may have  opened underneath the Sigil app and you did not notice the new icon in your taskbar that represents the python tk window.  Clicking on that new taskbar icon should force the gui filebrowser window to the front.  Alternatively, simply try minimizing the Sigil app Window to see the gui file browser.

Once you have selected a name and location for the newly created epub3, it will allow the plugin to finish.

When you hit Cancel it killed the gui filebrowser window and the plugin itself, resulting in the error message.

**Comment by dawnbuie** [comment]
magic! you are right!

well that was hard to miss. thanks for letting me know though. 

conversion complete

and thanks for the plugin.
