### ISSUE TITLE
Change `.html` file extensions to `.xhtml`

### ISSUE THREAD

**Issue by arthurattwell** [kevinhendricks/ePub3-itizer#4]
Fantastic plugin, thank you. Would it be possible to have it change `.html` file extensions to `.xhtml`, and update internal links accordingly? EPUB3 doesn't require `.xhtml`, but according to the spec

> The XHTML Content Document filename **should** use the file extension `.xhtml`.

So `.html` filename extensions throw a warning in EpubCheck.

**Comment by kevinhendricks** [comment]
You can do that quite easily in Sigil using the rename function to auto rename all .html to .xhtml extensions and auto fix all links, before firing up the ePub3-itizer plugin, so there was no need to duplicate all of that code in the plugin.

See the instructions on how to do that here (See "Before Conversion")
http://www.mobileread.com/forums/showpost.php?p=2973066&postcount=1

**Comment by kevinhendricks** [comment]
Closing this since this capability already exists as an automatic tool in Sigil.
