### ISSUE TITLE
Plugin error/failure

### ISSUE THREAD

**Issue by nashls** [kevinhendricks/ePub3-itizer#5]
When I try to run this in Sigil 1.0.0, I get the following error message: 

Status: failed

Traceback (most recent call last):
  File "/Applications/Sigil.app/Contents/plugin_launchers/python/launcher.py", line 134, in launch
    target_script = __import__(script_module)
  File "/Users/ln/Library/Application Support/sigil-ebook/sigil/plugins/ePub3-itizer/plugin.py", line 35, in <module>
    import tkinter
  File "tkinter/__init__.py", line 36, in <module>
ImportError: dlopen(/Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.6/Tcl
  Referenced from: /Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so
  Reason: image not found
Error: dlopen(/Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.6/Tcl
  Referenced from: /Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so
  Reason: image not found

This is my first time using Sigil plugins, and so I'm not sure if there's something I'm doing incorrectly, or if this is a bug. Any help would be really appreciated! I'm a publisher interested in upgrading all my old epub 2 files to epub 3 for accessibility reasons, but am feeling a little daunted by the task, given that we're a very small team. Thanks!

**Comment by kevinhendricks** [comment]
You need to read the release notes and as described install the correct version of ActiveState's ActiveTCL (look for version 8.6.9 or later) for your version of macOS.
