### ISSUE TITLE
Generated epub failes epubcheck - non-linear nav added to spine

### ISSUE THREAD

**Issue by YodaDaCoda** [kevinhendricks/ePub3-itizer#6]
It seems that when the epub has its own html toc, the `navid` should not be added to the spine - currently it is added with `linear="no"`

**Comment by kevinhendricks** [comment]
That depends on e-reader unfortunately.  Some take linear = no to not display that item.   Others ignore it and always display it.  It is a toss-up.

As a result many epub developers then hand merge the html toc into the epub3 nav as the nav can play both roles and then leaving as linear=no makes the most sense.

To make matters worse epubcheck has constantly changed its opinion of how things should be done in this regard.

Just hand edit the opf to fix things the way that works for your e-reader.  I personally hand merge the html toc into the nav.
